"""empty message

Revision ID: 02cab74c0d3f
Revises: 11ae371597cf
Create Date: 2019-04-21 21:43:25.873941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02cab74c0d3f'
down_revision = '11ae371597cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('liftermaster', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('liftermaster', 'year')
    # ### end Alembic commands ###
