"""empty message

Revision ID: 11ae371597cf
Revises: 7b7eed798f1c
Create Date: 2019-04-02 22:31:53.088473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11ae371597cf'
down_revision = '7b7eed798f1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitions', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitions', 'type')
    # ### end Alembic commands ###
