"""empty message

Revision ID: 3c76e3fe94e8
Revises: 02cab74c0d3f
Create Date: 2019-04-21 21:53:11.962987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c76e3fe94e8'
down_revision = '02cab74c0d3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('liftermaster', sa.Column('club_single', sa.String(), nullable=True))
    op.add_column('liftermaster', sa.Column('club_single_short', sa.String(), nullable=True))
    op.add_column('liftermaster', sa.Column('club_team', sa.String(), nullable=True))
    op.add_column('liftermaster', sa.Column('club_team_short', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('liftermaster', 'club_team_short')
    op.drop_column('liftermaster', 'club_team')
    op.drop_column('liftermaster', 'club_single_short')
    op.drop_column('liftermaster', 'club_single')
    # ### end Alembic commands ###
