"""empty message

Revision ID: 68c07b9a1489
Revises: 6d0b0a742638
Create Date: 2019-06-08 22:34:29.570915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c07b9a1489'
down_revision = '6d0b0a742638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('association', sa.Column('cj_points', sa.Integer(), nullable=True))
    op.add_column('association', sa.Column('snatch_points', sa.Integer(), nullable=True))
    op.drop_column('association', 'points')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('association', sa.Column('points', sa.INTEGER(), nullable=True))
    op.drop_column('association', 'snatch_points')
    op.drop_column('association', 'cj_points')
    # ### end Alembic commands ###
