"""empty message

Revision ID: 9b1e0fc3fcff
Revises: 
Create Date: 2018-10-14 18:51:41.962662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b1e0fc3fcff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('short', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weightclass',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sex', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('min_weight', sa.Float(), nullable=True),
    sa.Column('max_weight', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lifters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('sinclair_factor', sa.Float(), nullable=True),
    sa.Column('sex', sa.Boolean(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('weightclass_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['weightclass_id'], ['weightclass.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lifter_id', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=True),
    sa.Column('result', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lifter_id'], ['lifters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('current',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lifter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lifter_id'], ['lifters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('current')
    op.drop_table('attempts')
    op.drop_table('lifters')
    op.drop_table('weightclass')
    op.drop_table('teams')
    # ### end Alembic commands ###
