"""empty message

Revision ID: bfd41dd7aefa
Revises: 269da9466393
Create Date: 2020-03-23 19:38:51.783564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfd41dd7aefa'
down_revision = '269da9466393'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitions', sa.Column('external_timer', sa.Boolean(), server_default='t', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitions', 'external_timer')
    # ### end Alembic commands ###
