"""empty message

Revision ID: dd68878fe37c
Revises: 
Create Date: 2019-06-08 22:40:23.724445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd68878fe37c'
down_revision = None
branch_labels = None
depends_on = None
 

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('youtube_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('liftermaster',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('sex', sa.Boolean(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('club_single', sa.String(), nullable=True),
    sa.Column('club_single_short', sa.String(), nullable=True),
    sa.Column('club_team', sa.String(), nullable=True),
    sa.Column('club_team_short', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('short', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weightclass',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sex', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('min_weight', sa.Float(), nullable=True),
    sa.Column('max_weight', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association',
    sa.Column('left_id', sa.Integer(), nullable=False),
    sa.Column('right_id', sa.Integer(), nullable=False),
    sa.Column('snatch_points', sa.Integer(), nullable=True),
    sa.Column('cj_points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['left_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['right_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('left_id', 'right_id')
    )
    op.create_table('lifters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lifter_id', sa.String(), nullable=True),
    sa.Column('competition_id', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('sinclair_factor', sa.Float(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('weightclass_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['lifter_id'], ['liftermaster.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['weightclass_id'], ['weightclass.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lifter_id', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=True),
    sa.Column('result', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lifter_id'], ['lifters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('current',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lifter_id', sa.Integer(), nullable=True),
    sa.Column('test', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lifter_id'], ['lifters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('current')
    op.drop_table('attempts')
    op.drop_table('lifters')
    op.drop_table('association')
    op.drop_table('weightclass')
    op.drop_table('teams')
    op.drop_table('liftermaster')
    op.drop_table('competitions')
    # ### end Alembic commands ###
